// Signature Immersive Experience (SIE)
// A hybrid, interdisciplinary experiential learning programme combining a VIRTUAL
// phase with an IN-COUNTRY IMMERSION (Kenya, 2026 cohort). Designed for non-clinical
// Health Missions students to gain direct exposure to how health systems function,
// how innovation is applied in practice, and what employment pathways exist —
// through site visits, partner-defined projects and structured reflection.

export const SIE_PHASES = ["Virtual Phase", "In-Country Immersion"] as const;
export type SiePhase = typeof SIE_PHASES[number];

/** The three pillars of the immersion experience. */
export const SIE_ACTIVITIES = ["Site Visits", "Partner Projects", "Structured Reflection"] as const;
export type SieActivity = typeof SIE_ACTIVITIES[number];

/** Exposure outcomes the programme is designed to produce. */
export const SIE_EXPOSURE_AREAS = [
  "Health System Function",
  "Innovation in Practice",
  "Employment Pathways",
] as const;
export type SieExposureArea = typeof SIE_EXPOSURE_AREAS[number];

/** Academic backgrounds — the programme is explicitly interdisciplinary & non-clinical. */
export const SIE_DISCIPLINES = [
  "Business & Entrepreneurship",
  "Computer Science",
  "Engineering",
  "Social Sciences",
  "Public Policy",
  "Data Science",
] as const;
export type SieDiscipline = typeof SIE_DISCIPLINES[number];

import { HEALTH_INTEREST_AREAS, generateHealthInterests, getHealthInterestDistribution } from "../hemp-health-interests";

export interface SieCohort {
  id: string;
  name: string;
  year: number;
  country: string;
  region?: "East Africa" | "West Africa" | "Southern Africa" | "Central Africa";
  /** Recruitment / participation funnel */
  applied: number;
  selected: number;
  completedVirtual: number;
  travelledInCountry: number;
  completedProgramme: number;
  female: number;
  /** Delivery volume */
  siteVisits: number;
  partnerOrgs: number;
  partnerProjects: number;
  reflectionSessions: number;
  /** Self-reported exposure gain, out of 5, per exposure area */
  exposure: Record<SieExposureArea, number>;
  /** Participants by academic discipline */
  disciplines: Record<SieDiscipline, number>;
  /** Hours delivered in each phase */
  hours: Record<SiePhase, number>;
  /** Outcomes generated by the immersion */
  employmentLeads: number;
  projectsAdopted: number;   // partner-defined projects taken forward by the host
  satisfaction: number;      // out of 5
  /** Participant Feedback Metrics (from feedback form) */
  relevance: number;         // out of 5
  quality: number;           // out of 5
  usefulness: number;        // out of 5
  confidence: number;        // out of 5
  nps: number;               // Net Promoter Score 0-10
  completionFullProgramme: number;  // % who completed both virtual and in-person
  /** Career Clarity and Next Steps */
  careerClarityPct: number;   // % who gained clarity on career direction
  /** NPS Distribution */
  npsPromoters: number;       // % scoring 9-10
  npsPassives: number;        // % scoring 7-8
  npsDetractors: number;      // % scoring 0-6
  /** Diversity Metrics */
  pwd: number;                // Number of participants with disabilities
  idpRefugees: number;        // Number of IDP/Refugee participants
  /** Employment & Internship Placements (post-SIE outcomes) */
  employmentPlacements: number;    // Number securing employment post-SIE
  internshipPlacements: number;    // Number securing internships post-SIE
  placementConversionRate: number; // % of participants securing placements
  /** SIE Performance Tracking */
  overallPerformanceScore: number; // Overall programme performance (0-100)
  learningOutcomesScore: number;   // Average learning outcomes achievement (0-100)
  participantEngagement: number;   // Engagement level (0-100)
  targetAchievementRate: number;   // % of programme targets achieved
  /** Health Interest Areas */
  healthInterests: Record<string, number>; // Distribution of participants by health interest area
}

export const sieCohorts: SieCohort[] = [
  {
    id: "SIE01", name: "SIE Pilot Cohort", year: 2024, country: "Rwanda", region: "East Africa",
    applied: 64, selected: 24, completedVirtual: 22, travelledInCountry: 20, completedProgramme: 19,
    female: 11,
    siteVisits: 6, partnerOrgs: 5, partnerProjects: 5, reflectionSessions: 8,
    exposure: { "Health System Function": 4.1, "Innovation in Practice": 4.0, "Employment Pathways": 3.7 },
    disciplines: {
      "Business & Entrepreneurship": 7, "Computer Science": 4, "Engineering": 3,
      "Social Sciences": 4, "Public Policy": 3, "Data Science": 3,
    },
    hours: { "Virtual Phase": 32, "In-Country Immersion": 60 },
    employmentLeads: 6, projectsAdopted: 2, satisfaction: 4.2,
    relevance: 4.0, quality: 4.1, usefulness: 3.9, confidence: 4.0, nps: 7.8, completionFullProgramme: 79,
    careerClarityPct: 74, npsPromoters: 47, npsPassives: 42, npsDetractors: 11,
    pwd: 2, idpRefugees: 1,
    employmentPlacements: 5, internshipPlacements: 8, placementConversionRate: 68,
    overallPerformanceScore: 78, learningOutcomesScore: 82, participantEngagement: 75, targetAchievementRate: 85,
    healthInterests: { "Digital Health": 5, "Mental Health": 4, "Health Equity, Advocacy and Leadership": 3, "Nutrition": 3, "Disease Prevention and Control": 2, "Maternal and Child Health": 2, "One Health": 1 },
  },
  {
    id: "SIE02", name: "SIE Cohort II", year: 2025, country: "Rwanda", region: "East Africa",
    applied: 98, selected: 32, completedVirtual: 30, travelledInCountry: 28, completedProgramme: 27,
    female: 15,
    siteVisits: 9, partnerOrgs: 7, partnerProjects: 8, reflectionSessions: 12,
    exposure: { "Health System Function": 4.4, "Innovation in Practice": 4.3, "Employment Pathways": 4.0 },
    disciplines: {
      "Business & Entrepreneurship": 9, "Computer Science": 6, "Engineering": 4,
      "Social Sciences": 5, "Public Policy": 4, "Data Science": 4,
    },
    hours: { "Virtual Phase": 40, "In-Country Immersion": 72 },
    employmentLeads: 11, projectsAdopted: 4, satisfaction: 4.5,
    relevance: 4.3, quality: 4.4, usefulness: 4.2, confidence: 4.3, nps: 8.1, completionFullProgramme: 84,
    careerClarityPct: 81, npsPromoters: 56, npsPassives: 38, npsDetractors: 6,
    pwd: 3, idpRefugees: 2,
    employmentPlacements: 9, internshipPlacements: 14, placementConversionRate: 76,
    overallPerformanceScore: 86, learningOutcomesScore: 89, participantEngagement: 84, targetAchievementRate: 92,
    healthInterests: { "Mental Health": 6, "Digital Health": 5, "Health Equity, Advocacy and Leadership": 4, "Nutrition": 4, "Disease Prevention and Control": 3, "Maternal and Child Health": 2, "Sexual and Reproductive Health": 2, "One Health": 1 },
  },
  {
    id: "SIE03", name: "SIE Cohort III - Kenya", year: 2024, country: "Kenya", region: "East Africa",
    applied: 75, selected: 28, completedVirtual: 26, travelledInCountry: 24, completedProgramme: 22,
    female: 13,
    siteVisits: 7, partnerOrgs: 6, partnerProjects: 6, reflectionSessions: 10,
    exposure: { "Health System Function": 4.2, "Innovation in Practice": 4.1, "Employment Pathways": 3.9 },
    disciplines: {
      "Business & Entrepreneurship": 8, "Computer Science": 5, "Engineering": 4,
      "Social Sciences": 5, "Public Policy": 3, "Data Science": 3,
    },
    hours: { "Virtual Phase": 36, "In-Country Immersion": 66 },
    employmentLeads: 7, projectsAdopted: 3, satisfaction: 4.3,
    relevance: 4.1, quality: 4.2, usefulness: 4.0, confidence: 4.1, nps: 8.0, completionFullProgramme: 81,
    careerClarityPct: 77, npsPromoters: 50, npsPassives: 40, npsDetractors: 10,
    pwd: 2, idpRefugees: 1,
    employmentPlacements: 6, internshipPlacements: 10, placementConversionRate: 72,
    overallPerformanceScore: 82, learningOutcomesScore: 85, participantEngagement: 80, targetAchievementRate: 88,
    healthInterests: { "Digital Health": 4, "Health Equity, Advocacy and Leadership": 3, "Mental Health": 3, "Nutrition": 3, "Disease Prevention and Control": 2, "Maternal and Child Health": 2, "One Health": 2 },
  },
  {
    id: "SIE04", name: "SIE Cohort IV - Ghana", year: 2025, country: "Ghana", region: "West Africa",
    applied: 82, selected: 30, completedVirtual: 28, travelledInCountry: 26, completedProgramme: 24,
    female: 14,
    siteVisits: 8, partnerOrgs: 6, partnerProjects: 7, reflectionSessions: 11,
    exposure: { "Health System Function": 4.3, "Innovation in Practice": 4.2, "Employment Pathways": 4.0 },
    disciplines: {
      "Business & Entrepreneurship": 9, "Computer Science": 5, "Engineering": 4,
      "Social Sciences": 6, "Public Policy": 3, "Data Science": 3,
    },
    hours: { "Virtual Phase": 38, "In-Country Immersion": 70 },
    employmentLeads: 8, projectsAdopted: 3, satisfaction: 4.4,
    relevance: 4.2, quality: 4.3, usefulness: 4.1, confidence: 4.2, nps: 8.2, completionFullProgramme: 83,
    careerClarityPct: 79, npsPromoters: 52, npsPassives: 39, npsDetractors: 9,
    pwd: 2, idpRefugees: 2,
    employmentPlacements: 7, internshipPlacements: 11, placementConversionRate: 75,
    overallPerformanceScore: 84, learningOutcomesScore: 87, participantEngagement: 82, targetAchievementRate: 90,
    healthInterests: { "Mental Health": 5, "Digital Health": 4, "Health Equity, Advocacy and Leadership": 4, "Nutrition": 3, "Disease Prevention and Control": 3, "Maternal and Child Health": 2, "Sexual and Reproductive Health": 2 },
  },
];

/** Individual site visits made during the in-country immersion. */
export interface SieSiteVisit {
  id: string;
  cohortId: string;
  host: string;
  hostType: "Referral Hospital" | "Health Startup" | "Regulator / Ministry" | "Research Institute" | "Health Manufacturer";
  year: number;
  country: string;
  students: number;
  /** Which exposure area this visit was designed to deliver */
  focus: SieExposureArea;
  insightScore: number; // student-rated value of the visit, out of 5
}

export const sieSiteVisits: SieSiteVisit[] = [
  { id: "SV01", cohortId: "SIE01", host: "King Faisal Hospital",        hostType: "Referral Hospital",    year: 2024, country: "Rwanda", students: 20, focus: "Health System Function", insightScore: 4.3 },
  { id: "SV02", cohortId: "SIE01", host: "Babyl Rwanda",                hostType: "Health Startup",       year: 2024, country: "Rwanda", students: 20, focus: "Innovation in Practice", insightScore: 4.4 },
  { id: "SV03", cohortId: "SIE01", host: "Rwanda FDA",                  hostType: "Regulator / Ministry", year: 2024, country: "Rwanda", students: 19, focus: "Health System Function", insightScore: 3.9 },
  { id: "SV04", cohortId: "SIE01", host: "Rwanda Biomedical Centre",    hostType: "Research Institute",   year: 2024, country: "Rwanda", students: 18, focus: "Employment Pathways",    insightScore: 3.8 },
  { id: "SV05", cohortId: "SIE01", host: "Zipline Distribution Centre", hostType: "Health Startup",       year: 2024, country: "Rwanda", students: 20, focus: "Innovation in Practice", insightScore: 4.7 },
  { id: "SV06", cohortId: "SIE01", host: "BioNTech Kigali",             hostType: "Health Manufacturer",  year: 2024, country: "Rwanda", students: 17, focus: "Employment Pathways",    insightScore: 4.1 },

  { id: "SV07", cohortId: "SIE02", host: "King Faisal Hospital",        hostType: "Referral Hospital",    year: 2025, country: "Rwanda", students: 28, focus: "Health System Function", insightScore: 4.4 },
  { id: "SV08", cohortId: "SIE02", host: "Zipline Distribution Centre", hostType: "Health Startup",       year: 2025, country: "Rwanda", students: 28, focus: "Innovation in Practice", insightScore: 4.8 },
  { id: "SV09", cohortId: "SIE02", host: "Rwanda FDA",                  hostType: "Regulator / Ministry", year: 2025, country: "Rwanda", students: 26, focus: "Health System Function", insightScore: 4.1 },
  { id: "SV10", cohortId: "SIE02", host: "BioNTech Kigali",             hostType: "Health Manufacturer",  year: 2025, country: "Rwanda", students: 27, focus: "Employment Pathways",    insightScore: 4.3 },
  { id: "SV11", cohortId: "SIE02", host: "Rwanda Biomedical Centre",    hostType: "Research Institute",   year: 2025, country: "Rwanda", students: 25, focus: "Health System Function", insightScore: 4.0 },
  { id: "SV12", cohortId: "SIE02", host: "Babyl Rwanda",                hostType: "Health Startup",       year: 2025, country: "Rwanda", students: 28, focus: "Innovation in Practice", insightScore: 4.5 },
  { id: "SV13", cohortId: "SIE02", host: "Ministry of Health Rwanda",   hostType: "Regulator / Ministry", year: 2025, country: "Rwanda", students: 24, focus: "Employment Pathways",    insightScore: 4.2 },
  { id: "SV14", cohortId: "SIE02", host: "Kigali Health Institute",     hostType: "Research Institute",   year: 2025, country: "Rwanda", students: 26, focus: "Health System Function", insightScore: 4.1 },
  { id: "SV15", cohortId: "SIE02", host: "Insightiv AI",                hostType: "Health Startup",       year: 2025, country: "Rwanda", students: 27, focus: "Innovation in Practice", insightScore: 4.6 },
];
